# Generated by Django 4.1.2 on 2022-10-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='cantidad_hermanos',
        ),
        migrations.AddField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(default=0.0004950495049504951, max_length=50),
            preserve_default=False,
        ),
    ]
