# Generated by Django 4.1.2 on 2022-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_familia_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdadCalculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_calculada', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='parentesco',
            new_name='apellido',
        ),
    ]
